# Generated by Django 2.2.1 on 2019-05-18 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crewmate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ship', models.CharField(choices=[('S', 'Sloop'), ('B', 'Brig'), ('G', 'Galleon')], max_length=10)),
                ('treasure', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('E', 'Extraordinary')], max_length=10)),
                ('tears', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('E', 'Extraordinary')], max_length=10)),
                ('enemyCrewSize', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('crew', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('island', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='log.Island')),
            ],
        ),
    ]
