# Generated by Django 2.2.1 on 2019-06-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190531_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='island',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='islandName', to='log.Island'),
        ),
    ]
