# Generated by Django 2.2.2 on 2019-06-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190602_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tears',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('E', 'Extraordinary')], default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='treasure',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('E', 'Extraordinary')], default='U', max_length=10),
        ),
    ]
