# Generated by Django 2.2.1 on 2019-05-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20190518_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='island',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='log.Island'),
        ),
    ]
