# Generated by Django 2.2.2 on 2019-06-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verificationCode',
            field=models.CharField(default='aaaaaa', max_length=6),
            preserve_default=False,
        ),
    ]
