# Generated by Django 2.2.1 on 2019-05-26 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20190518_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='videoURL',
            field=models.URLField(default='http://www.youtube.com', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
