# Generated by Django 2.2.1 on 2019-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20190526_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='videoURL',
            field=models.URLField(default='http://www.youtube.com', verbose_name='URL'),
        ),
    ]
