# Generated by Django 2.2.2 on 2019-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20190613_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='enemyShip',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'Sloop'), ('B', 'Brig'), ('G', 'Galleon'), ('K', 'Karen'), ('M', 'Meg'), ('SK', 'Skelleon'), ('F', 'Fort'), ('SC', 'Ship Cloud')], default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='myShip',
            field=models.CharField(choices=[('U', 'Unknown'), ('S', 'Sloop'), ('B', 'Brig'), ('G', 'Galleon'), ('K', 'Karen'), ('M', 'Meg'), ('SK', 'Skelleon'), ('F', 'Fort'), ('SC', 'Ship Cloud')], default='U', max_length=10),
        ),
    ]
