# Generated by Django 2.2.1 on 2019-05-26 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='crew',
            field=models.ManyToManyField(related_name='crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
