# Generated by Django 2.2.1 on 2019-05-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20190526_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='ship',
            new_name='myShip',
        ),
    ]
