# Generated by Django 2.2.1 on 2019-05-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20190526_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log.Entry')),
            ],
            bases=('log.entry',),
        ),
    ]
