# Generated by Django 2.2.1 on 2019-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_entry_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamertag',
            field=models.CharField(default='Missing', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='crew',
            field=models.ManyToManyField(to='log.Profile'),
        ),
    ]
