# Generated by Django 2.2.1 on 2019-05-31 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20190531_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.Profile'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='crew',
            field=models.ManyToManyField(related_name='crewMembers', to='log.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, to='log.Profile'),
        ),
    ]
