# Generated by Django 2.2.1 on 2019-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20190531_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='log.Profile'),
        ),
    ]
