# Generated by Django 2.2.1 on 2019-05-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_auto_20190531_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='crew',
            field=models.ManyToManyField(related_name='crewNames', to='log.Profile'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='island',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='islandName', to='log.Island'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='myFriends', to='log.Profile'),
        ),
    ]
